### ISSUE TITLE
Add example for deterministic sign specifying a nonce

### ISSUE THREAD

**Issue by 0T34** [Microsoft/Picnic#7]
Hi, I'm working with this piece of code currently:

```
bool CKey::Sign(const uint256 &hash, std::vector<unsigned char>& vchSig, uint32_t test_case) const {
    if (!fValid)
        return false;
    vchSig.resize(72);
    RFC6979_HMAC_SHA256 prng(begin(), 32, (unsigned char*)&hash, 32);
    do {
        uint256 nonce;
        prng.Generate((unsigned char*)&nonce, 32);
        nonce += test_case;
        int nSigLen = 72;
        int ret = secp256k1_ecdsa_sign((const unsigned char*)&hash, 32, (unsigned char*)&vchSig[0], &nSigLen, begin(), (unsigned char*)&nonce);
        nonce = 0;
        if (ret) {
            vchSig.resize(nSigLen);
            return true;
        }
    } while(true);
}
```
Where **secp256k1_ecdsa_sign** prototype is:
```
int secp256k1_ecdsa_sign(const unsigned char *msg, int msglen, unsigned char *sig, int *siglen, const unsigned char *seckey, const unsigned char *nonce)
```
And, im trying to replace EC with Picnic, but I can't find a way to specify a noce in the code, I saw it in the [signature2 struct](https://github.com/microsoft/Picnic/blob/master/picnic3_impl.h#L30) but there is not example of the use of this structure.

**Comment by zaverucha** [comment]
hi @0T34 
The Picnic spec and implementations do not allow callers to specify the nonce.  This is the reference implementation and signing is deterministic. So you can test your implementation with the provided known-answer tests (see kats_test.c).  

The [optimized implementation](https://github.com/IAIK/Picnic) is much faster and is constant-time, the implementation we recommend using for prototyping.  In that implementation signing is also deterministic.

**Comment by 0T34** [comment]
Thanks for the information.
